### ISSUE TITLE
Documentation issue / something missing

### ISSUE THREAD

**Issue by hollerith** [s4n7h0/Halcyon#5]
Hi there,

The build instructions contain some errors I think. 

```$ ant ```

..builds okay

```
$ java -cp /opt/Halcyon/src/lib/autocomplete.jar:/opt/Halcyon/src/lib/rsyntaxtextarea.jar:/opt/Halcyon/dist/Halcyon_IDE_v2.0.1.jar halcyon.ide.HalcyonIDE 
Error: Could not find or load main class halcyon.ide.HalcyonIDE
```
There is nothing putting anything in /opt  when I try to just run the jar file from ./dist :

````
$ java -jar Halcyon_IDE_v2.0.1.jar
Exception in thread "main" java.lang.NoClassDefFoundError: org/fife/ui/rsyntaxtextarea/RSyntaxTextArea
        at halcyon.ide.HalcyonIDE.main(HalcyonIDE.java:19)
Caused by: java.lang.ClassNotFoundException: org.fife.ui.rsyntaxtextarea.RSyntaxTextArea
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 1 more
````

**Comment by s4n7h0** [comment]
@hollerith did you check the updates ? let me know if you still face issues.
